"""empty message

Revision ID: 558df7bfb739
Revises: 28c0084cf427
Create Date: 2018-08-01 20:35:21.604923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558df7bfb739'
down_revision = '28c0084cf427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('scan', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'scan')
    # ### end Alembic commands ###
